# Generated by Django 5.2 on 2025-04-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0002_accessory_car_customer_payment_rental_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
