# Generated by Django 5.2 on 2025-04-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0003_user_is_staff"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="chk_user_at_least_one_role",
        ),
    ]
