# Generated by Django 5.2 on 2025-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("car_app", "0004_remove_user_chk_user_at_least_one_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="chk_user_not_both_roles",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_owner",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_customer", True), ("is_owner", True), _negated=True
                ),
                name="chk_user_not_both_roles",
            ),
        ),
    ]
