# Generated by Django 5.2 on 2025-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0005_remove_user_chk_user_not_both_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
