# Generated by Django 5.2 on 2025-05-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0006_alter_rental_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="accessories",
        ),
        migrations.DeleteModel(
            name="Accessory",
        ),
    ]
