# Generated by Django 5.2 on 2025-05-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0007_remove_rental_accessories_delete_accessory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="rental",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="car_app.rental",
            ),
        ),
    ]
