# Generated by Django 5.2 on 2025-05-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0008_alter_payment_rental"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="chk_user_not_both_roles",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_customer",
        ),
    ]
