# Generated by Django 5.2 on 2025-05-25 13:50

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0009_remove_user_chk_user_not_both_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=phone_field.models.PhoneField(
                default="", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
