name: workflow.yml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_image:
        description: "Build Docker image?"
        required: false
        default: "true"
        type: choice
        options: [ "true", "false" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "patryka2000/car-rental"


jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          printf '%s\n' "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

  build:
    name: "Docker"
    needs: test
    if: >-
      github.event_name == 'push' ||
      github.event.inputs.build_image == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
