name: workflow.yml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_image:
        description: "Build Docker image?"
        required: false
        default: "true"
        type: choice
        options: [ "true", "false" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  test:
    name: "Lint & Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          printf '%s\n' "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies + dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black

      - name: Run pytest
        run: pytest -q

  build:
    name: "Build & Push Docker image"
    needs: test
    if: >-
      github.event_name == 'push' ||
      github.event.inputs.build_image == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}


